name: Deploy to AWS

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install Node.js
        run: 'sudo apt update -y && curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh && sudo bash /tmp/nodesource_setup.sh && sudo apt install nodejs -y && node -v && npm i -g npm && npm -v'

      - name: Install AWS CDK
        run: 'npm i -g aws-cdk'

      - name: Install project dependencies
        run: 'npm ci && npm ls'

      - name: CDK Synth
        run: 'cdk synth'
        working-directory: '.'

      - name: CDK Deploy
        run: 'cdk deploy'
        working-directory: '.'
